# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: paddle.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpaddle.proto\x12\x0c\x62rickbreaker\"4\n\tPaddleOut\x12\x10\n\x08\x64istance\x18\x01 \x01(\x01\x12\x15\n\rbuttonClicked\x18\x02 \x01(\x08\"e\n\x08PaddleIn\x12)\n\x04\x62uzz\x18\x01 \x01(\x0b\x32\x1b.brickbreaker.PaddleIn.Buzz\x1a.\n\x04\x42uzz\x12\x0e\n\x06motors\x18\x01 \x03(\x05\x12\x16\n\x0e\x64urationMillis\x18\x02 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'paddle_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PADDLEOUT._serialized_start=30
  _PADDLEOUT._serialized_end=82
  _PADDLEIN._serialized_start=84
  _PADDLEIN._serialized_end=185
  _PADDLEIN_BUZZ._serialized_start=139
  _PADDLEIN_BUZZ._serialized_end=185
# @@protoc_insertion_point(module_scope)
